### ISSUE TITLE
Docker GPU Not Available

### ISSUE THREAD

**Issue by CiSong10** [prs-eth/PanopticSegForLargeScalePointCloud#20]
Dear developer,

Thank you for uploading the Dockerfile. However, it says `The NVIDIA Driver was not detected.  GPU functionality will not be available.` after I built it without modification:

```
$ docker run <image_name>

==========
== CUDA ==
==========

CUDA Version 11.1.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use the NVIDIA Container Toolkit to start this container with GPU support; see
   https://docs.nvidia.com/datacenter/cloud-native/ .
```

**Comment by bxiang233** [comment]
> Dear developer,
> 
> Thank you for uploading the Dockerfile. However, it says `The NVIDIA Driver was not detected. GPU functionality will not be available.` after I built it without modification:
> 
> ```
> $ docker run <image_name>
> 
> ==========
> == CUDA ==
> ==========
> 
> CUDA Version 11.1.1
> 
> Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
> 
> This container image and its contents are governed by the NVIDIA Deep Learning Container License.
> By pulling and using the container, you accept the terms and conditions of this license:
> https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
> 
> A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.
> 
> WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
>    Use the NVIDIA Container Toolkit to start this container with GPU support; see
>    https://docs.nvidia.com/datacenter/cloud-native/ .
> ```

It appears because the host hasn’t passed its NVIDIA driver + GPU into the container.
Fix = (1) install the proper NVIDIA driver on the host, (2) install nvidia-container-toolkit, and (3) run the container with --gpus all.

**Comment by CiSong10** [comment]
Thank you! That works
